window.AA_I18N = {
        ru: {
            head: 'АА КАЗАХСТАНА', total: 'Всего:', units: [['год','года','лет'],['мес.','мес.','мес.'],['день','дня','дней']],
            motLab: 'Ежедневные размышления', kaspi: 'Седьмая Традиция', kaspiNote: 'Добровольное пожертвование в фонд АА Казахстана', nav: ['Сегодня','Новости','Книги','Группы'], allCities: 'Все города', favorites: '★ Избранное', noFavorites: 'Добавьте нужные группы в избранное, нажав на звезду в карточке.', addFavorite: 'Добавить в избранное', removeFavorite: 'Убрать из избранного',
            sOpen: 'ОТКРЫТО. ЕЩЕ', sSoon: 'ЧЕРЕЗ', sClosed: 'ЗАКРЫТО', todayBtn: '📅 Сегодня', sosMain: '🚨 НУЖНА ПОМОЩЬ?',
            sosRu: 'РУССКИЙ ЯЗЫК', sosKz: 'ҚАЗАҚ ТІЛІ', nProf: 'Мой путь', trustHead: 'ДОВЕРЕННЫЕ ЛИЦА', prayerHead: 'МОЛИТВА', notesHead: 'ЗАМЕТКИ ПО ДНЮ',
            nextMedal: 'До медали', left: 'Осталось', prayer: 'Боже, дай мне разум и душевный покой принять то, что я не в силах изменить,\nмужество изменить то, что могу,\nи мудрость отличить одно от другого.',
            placeholder: 'Ваши мысли, благодарности или инсайты...', litCom: 'Литературный комитет', litPrice: 'Наличие, цены и заказ литературы', bookAll: 'Все', bookRu: 'Рус', bookKz: 'Қаз', bookBuy: 'Купить', bookCall: 'Позвонить', bookShare: 'Поделиться',
            trustName: 'Имя', trustPhone: 'Номер', openMap: 'Открыть в 2ГИС', addressLabel: 'Адрес', scheduleLabel: 'Расписание', phoneLabel: 'Телефон', phonesLabel: 'Телефоны',
            openZoom: 'Открыть Zoom', openChat: 'Открыть чат', zoomLabel: 'Zoom', chatLabel: 'Чат', savePending: '...', saveDone: '✓ Сохранено',
            minutesShort: 'МИН', hoursShort: 'Ч', noSchedule: 'По запросу',
            notificationsHead: 'УВЕДОМЛЕНИЯ', notificationCenter: 'Уведомления', notificationReadAll: 'Прочитать все', notificationEmpty: 'Здесь появятся новые размышления, новости и напоминания о собраниях.',
            notifMasterTitle: 'Внутренние уведомления', notifMasterNote: 'Показывать новые события в центре уведомлений', notifReflectionTitle: 'Ежедневные размышления', notifReflectionNote: 'Сообщать о новом размышлении при открытии приложения', notifNewsTitle: 'Новости', notifNewsNote: 'Сообщать о новых публикациях', notifTodayTitle: 'Группы сегодня', notifTodayNote: 'Показывать сводку собраний на текущий день', notifFavoritesTitle: 'Избранные группы', notifFavoritesNote: 'Напоминать перед началом собрания, пока приложение открыто', notifBrowserTitle: 'Системное окно при открытом приложении', notifBrowserNote: 'Не работает после полного закрытия приложения', notifBeforeTitle: 'Напоминать заранее',
            notifReflectionNew: 'Новое ежедневное размышление', notifNewsNew: 'Новая публикация', notifTodayNew: 'Собрания сегодня', notifFavoriteNew: 'Скоро начнётся собрание',
            soberUnitsShort: ['лет', 'мес.', 'дней'], quickToday: 'Найти собрание сегодня', quickCall: 'Позвонить в АА', quickFavorites: 'Мои группы', quickFirst: 'Я впервые в АА', nearestMeeting: 'Ближайшее собрание', nearestEmpty: 'Сегодня подходящих предстоящих собраний не найдено.', todayAt: 'Сегодня в', tomorrowAt: 'Завтра в', route: 'Маршрут', callAction: 'Позвонить', details: 'Подробнее', myCity: 'Мой город', onlineFilter: 'Онлайн', chooseCityTitle: 'В каком городе вы находитесь?', chooseCityNote: 'Мы покажем ваши группы и ближайшее собрание.', saveCity: 'Сохранить город', showAllCities: 'Показать все города', firstTitle: 'Первый раз в АА', firstText: 'Собрания бесплатные. Записываться не нужно. Можно ничего не говорить и просто слушать. Фамилию называть необязательно.', cityHead: 'МОЙ ГОРОД', citySettingTitle: 'Выберите свой город', citySettingNote: 'Он используется для ближайших собраний и уведомлений', cityChange: 'Изменить', cityNotSelected: 'Город не выбран', settingsHead: 'НАСТРОЙКИ', versionLabel: 'Версия приложения', updateLabel: 'Обновление применяется автоматически при запуске', textSizeTitle: 'Размер текста', textSizeNormal: 'Обычный', textSizeLarge: 'Крупный', statusUpdating: 'Обновляем данные…', statusUpdated: 'Данные обновлены', statusOffline: 'Нет интернета. Показана сохранённая версия', statusZoomFailed: 'Не удалось открыть Zoom', statusNoPhone: 'Номер телефона не указан', understood: 'Понятно', reportError: 'Сообщить об ошибке', scheduleUpdated: 'Расписание обновлено', newsChecked: 'Новости проверены', newsImageAlt: 'Новость АА Казахстана', newsCarouselLabel: 'Навигация по изображениям новости', newsOpenCard: number => `Открыть изображение ${number}`, newsCounter: (current, total) => `${current} из ${total}`
        },
        kz: {
            head: 'ҚАЗАҚСТАН АА', total: 'Барлығы:', units: [['жыл','жыл','жыл'],['ай','ай','ай'],['күн','күн','күн']],
            motLab: 'Күнделікті ойлар', kaspi: 'Жетінші Дәстүр', kaspiNote: 'Қазақстан АА қорына ерікті қайырымдылық', nav: ['Бүгін','Жаңалықтар','Кітаптар','Топтар'], allCities: 'Барлық қалалар', favorites: '★ Таңдаулылар', noFavorites: 'Қажетті топтарды карточкадағы жұлдызшаны басып таңдаулыларға қосыңыз.', addFavorite: 'Таңдаулыларға қосу', removeFavorite: 'Таңдаулылардан алып тастау',
            sOpen: 'АШЫҚ. ТАҒЫ', sSoon: 'БАСТАЛАДЫ', sClosed: 'ЖАБЫҚ', todayBtn: '📅 Бүгін', sosMain: '🚨 КӨМЕК КЕРЕК ПЕ?',
            sosRu: 'ОРЫС ТІЛІ', sosKz: 'ҚАЗАҚ ТІЛІ', nProf: 'Менің жолым', trustHead: 'СЕНІМДІ ТҰЛҒАЛАР', prayerHead: 'ДҰҒА', notesHead: 'КҮНДЕЛІКТІ ЖАЗБАЛАР',
            nextMedal: 'Медальға дейін', left: 'Қалды', prayer: 'Уа, Тәңірім, мен өзгерте алмайтын нәрселерді қабылдауға жан тыныштығын,\nөзгерте алатын нәрселерді өзгертуге батылдық,\nжәне олардың айырмашылығын білетін даналық бере гөр.',
            placeholder: 'Ойларыңыз, ризашылықтарыңыз немесе инсайттарыңыз...', litCom: 'Әдебиет комитеті', litPrice: 'Әдебиеттің бар-жоғы, бағасы және тапсырыс', bookAll: 'Барлығы', bookRu: 'Рус', bookKz: 'Қаз', bookBuy: 'Сатып алу', bookCall: 'Қоңырау шалу', bookShare: 'Бөлісу',
            trustName: 'Аты', trustPhone: 'Нөмірі', openMap: '2ГИС ашу', addressLabel: 'Мекенжай', scheduleLabel: 'Кесте', phoneLabel: 'Телефон', phonesLabel: 'Телефондар',
            openZoom: 'Zoom ашу', openChat: 'Чатты ашу', zoomLabel: 'Zoom', chatLabel: 'Чат', savePending: '...', saveDone: '✓ Сақталды',
            minutesShort: 'МИН', hoursShort: 'САҒ', noSchedule: 'Сұраныс бойынша',
            notificationsHead: 'ХАБАРЛАМАЛАР', notificationCenter: 'Хабарламалар', notificationReadAll: 'Барлығын оқу', notificationEmpty: 'Мұнда жаңа ойлар, жаңалықтар және жиналыстар туралы еске салулар пайда болады.',
            notifMasterTitle: 'Ішкі хабарламалар', notifMasterNote: 'Жаңа оқиғаларды хабарламалар орталығында көрсету', notifReflectionTitle: 'Күнделікті ойлар', notifReflectionNote: 'Қосымша ашылғанда жаңа ой туралы хабарлау', notifNewsTitle: 'Жаңалықтар', notifNewsNote: 'Жаңа жарияланымдар туралы хабарлау', notifTodayTitle: 'Бүгінгі топтар', notifTodayNote: 'Бүгінгі жиналыстардың қорытындысын көрсету', notifFavoritesTitle: 'Таңдаулы топтар', notifFavoritesNote: 'Қосымша ашық кезде жиналыс алдында еске салу', notifBrowserTitle: 'Қосымша ашық кездегі жүйелік терезе', notifBrowserNote: 'Қосымша толық жабылғаннан кейін жұмыс істемейді', notifBeforeTitle: 'Алдын ала еске салу',
            notifReflectionNew: 'Жаңа күнделікті ой', notifNewsNew: 'Жаңа жарияланым', notifTodayNew: 'Бүгінгі жиналыстар', notifFavoriteNew: 'Жиналыс жақында басталады',
            soberUnitsShort: ['жыл', 'ай', 'күн'], quickToday: 'Бүгінгі жиналысты табу', quickCall: 'АА-ға қоңырау шалу', quickFavorites: 'Менің топтарым', quickFirst: 'Мен АА-ға алғаш рет келдім', nearestMeeting: 'Ең жақын жиналыс', nearestEmpty: 'Жақын уақытта қолайлы жиналыс табылмады.', todayAt: 'Бүгін', tomorrowAt: 'Ертең', route: 'Бағыт', callAction: 'Қоңырау шалу', details: 'Толығырақ', myCity: 'Менің қалам', onlineFilter: 'Онлайн', chooseCityTitle: 'Сіз қай қаладасыз?', chooseCityNote: 'Сіздің топтарыңыз бен ең жақын жиналысты көрсетеміз.', saveCity: 'Қаланы сақтау', showAllCities: 'Барлық қалаларды көрсету', firstTitle: 'АА-ға алғаш рет', firstText: 'Жиналыстар тегін. Алдын ала жазылудың қажеті жоқ. Ештеңе айтпай, жай ғана тыңдауға болады. Тегіңізді айту міндетті емес.', cityHead: 'МЕНІҢ ҚАЛАМ', citySettingTitle: 'Қалаңызды таңдаңыз', citySettingNote: 'Ол ең жақын жиналыстар мен хабарламалар үшін қолданылады', cityChange: 'Өзгерту', cityNotSelected: 'Қала таңдалмаған', settingsHead: 'БАПТАУЛАР', versionLabel: 'Қосымша нұсқасы', updateLabel: 'Жаңарту қосымша іске қосылғанда автоматты түрде қолданылады', textSizeTitle: 'Мәтін өлшемі', textSizeNormal: 'Қалыпты', textSizeLarge: 'Үлкен', statusUpdating: 'Деректер жаңартылуда…', statusUpdated: 'Деректер жаңартылды', statusOffline: 'Интернет жоқ. Сақталған нұсқа көрсетілді', statusZoomFailed: 'Zoom ашылмады', statusNoPhone: 'Телефон нөмірі көрсетілмеген', understood: 'Түсінікті', reportError: 'Қате туралы хабарлау', scheduleUpdated: 'Кесте жаңартылды', newsChecked: 'Жаңалықтар тексерілді', newsImageAlt: 'Қазақстан АА жаңалығы', newsCarouselLabel: 'Жаңалық суреттерінің навигациясы', newsOpenCard: number => `${number}-суретті ашу`, newsCounter: (current, total) => `${current} / ${total}`
        },
        en: {
            head: 'AA KAZAKHSTAN', total: 'Total:', units: [['year','years','years'],['mo.','mo.','mo.'],['day','days','days']],
            motLab: 'Daily Reflections', kaspi: 'Seventh Tradition', kaspiNote: 'Voluntary contribution to the AA Kazakhstan service fund', nav: ['Today','News','Books','Groups'], allCities: 'All cities', favorites: '★ Favorites', noFavorites: 'Add groups to Favorites by tapping the star on a group card.', addFavorite: 'Add to Favorites', removeFavorite: 'Remove from Favorites',
            sOpen: 'OPEN ·', sSoon: 'STARTS IN', sClosed: 'CLOSED', todayBtn: '📅 Today', sosMain: '🚨 NEED HELP?',
            sosRu: 'RUSSIAN', sosKz: 'KAZAKH', nProf: 'My Journey', trustHead: 'TRUSTED CONTACTS', prayerHead: 'PRAYER', notesHead: 'DAILY NOTES',
            nextMedal: 'Next milestone', left: 'Remaining', prayer: 'God, grant me the serenity to accept the things I cannot change,\ncourage to change the things I can,\nand wisdom to know the difference.',
            placeholder: 'Your thoughts, gratitude, or insights...', litCom: 'Literature Committee', litPrice: 'Availability, prices, and literature orders', bookAll: 'All', bookRu: 'RU', bookKz: 'KZ', bookBuy: 'Buy', bookCall: 'Call', bookShare: 'Share',
            trustName: 'Name', trustPhone: 'Number', openMap: 'Open in 2GIS', addressLabel: 'Address', scheduleLabel: 'Schedule', phoneLabel: 'Phone', phonesLabel: 'Phones',
            openZoom: 'Open Zoom', openChat: 'Open chat', zoomLabel: 'Zoom', chatLabel: 'Chat', savePending: '...', saveDone: '✓ Saved',
            minutesShort: 'MIN', hoursShort: 'HR', noSchedule: 'On request',
            notificationsHead: 'NOTIFICATIONS', notificationCenter: 'Notifications', notificationReadAll: 'Mark all read', notificationEmpty: 'New reflections, news, and meeting reminders will appear here.',
            notifMasterTitle: 'In-app notifications', notifMasterNote: 'Show new events in the notification center', notifReflectionTitle: 'Daily Reflections', notifReflectionNote: 'Notify me about a new reflection when the app opens', notifNewsTitle: 'News', notifNewsNote: 'Notify me about new posts', notifTodayTitle: 'Today’s groups', notifTodayNote: 'Show a summary of today’s meetings', notifFavoritesTitle: 'Favorite groups', notifFavoritesNote: 'Remind me before a meeting starts while the app is open', notifBrowserTitle: 'System notification while the app is open', notifBrowserNote: 'Does not work after the app is fully closed', notifBeforeTitle: 'Remind me in advance',
            notifReflectionNew: 'New Daily Reflection', notifNewsNew: 'New post', notifTodayNew: 'Meetings today', notifFavoriteNew: 'A meeting starts soon',
            soberUnitsShort: ['years', 'mo.', 'days'], quickToday: 'Find a meeting today', quickCall: 'Call AA', quickFavorites: 'My groups', quickFirst: 'I am new to AA', nearestMeeting: 'Nearest meeting', nearestEmpty: 'No suitable upcoming meetings were found today.', todayAt: 'Today at', tomorrowAt: 'Tomorrow at', route: 'Directions', callAction: 'Call', details: 'Details', myCity: 'My city', onlineFilter: 'Online', chooseCityTitle: 'Which city are you in?', chooseCityNote: 'We will show your groups and the nearest meeting.', saveCity: 'Save city', showAllCities: 'Show all cities', firstTitle: 'New to AA', firstText: 'Meetings are free. No registration is required. You may simply listen without speaking. You do not have to give your last name.', cityHead: 'MY CITY', citySettingTitle: 'Choose your city', citySettingNote: 'Used for nearby meetings and notifications', cityChange: 'Change', cityNotSelected: 'City not selected', settingsHead: 'SETTINGS', versionLabel: 'App version', updateLabel: 'Updates are applied automatically when the app starts', textSizeTitle: 'Text size', textSizeNormal: 'Standard', textSizeLarge: 'Large', statusUpdating: 'Updating data…', statusUpdated: 'Data updated', statusOffline: 'No internet connection. Showing the saved version', statusZoomFailed: 'Could not open Zoom', statusNoPhone: 'No phone number provided', understood: 'Got it', reportError: 'Report an error', scheduleUpdated: 'Schedule updated', newsChecked: 'News checked',
            structureTitle: 'AA KAZAKHSTAN STRUCTURE', structureHint: 'Tap to enlarge', structureImageLabel: 'AA Kazakhstan service structure', writeAction: 'Message',
            backupTitle: 'Backup', exportData: 'Export my data', restoreData: 'Restore data', installText: 'Install the AA Kazakhstan app on your phone', installAction: 'Install', closeAction: 'Close',
            firstRunLanguage: 'Choose a language', firstRunLanguageNote: 'You can change the language later at the top of the screen.', firstRunCity: 'Choose a city', firstRunCityNote: 'We will show nearby meetings.', firstRunGroup: 'Add a group to Favorites', firstRunGroupNote: 'You can skip this step.', firstRunBack: 'Back', firstRunNext: 'Next', firstRunDone: 'Done', firstRunProgress: step => `Step ${step} of 3`, chooseLater: 'Not now',
            newsOriginalNote: 'News is published in its original language.', newsEmpty: 'No news yet.', newsLoading: 'Loading news…', newsError: 'Could not load news.', newsImageAlt: 'AA Kazakhstan news', newsCarouselLabel: 'News image navigation', newsOpenCard: number => `Open image ${number}`, newsCounter: (current, total) => `${current} of ${total}`,
            reflectionLoading: 'Loading…', reflectionMissing: 'No reflection was found for today', reflectionError: 'Could not load Daily Reflections',
            reportGroupMessage: name => `Hello. I found inaccurate information about the “${name}” group in the AA Kazakhstan app.\n\nWhat information is incorrect: `,
            checkedToday: 'today', bookCopied: 'Book information copied', literatureShare: 'AA Kazakhstan Literature Committee', meetingCount: count => `${count} meetings`, onlineWord: 'online',
            backupRestored: 'Data restored. The app will restart.', backupRestoreFailed: 'Could not restore data from this file.', releaseTitle: 'AA Kazakhstan app version 2.0 is available', releaseText: 'New navigation, larger text, new group buttons, notifications, backup, and other improvements.',
            scheduleDate: 'September 28, 2026', minuteOptions: ['15 min','30 min','1 hour','2 hours']
        }
    };


Object.assign(window.AA_I18N.ru, {
    closeAction: 'Закрыть', closeTip: 'Закрыть подсказку', clearSearch: 'Очистить поиск', mainNavigation: 'Основная навигация', logoAlt: 'Логотип АА Казахстана', qrAlt: 'QR-код приложения АА Казахстана', literatureCall: 'Позвонить Вячеславу',
    minuteOptions: ['15 мин', '30 мин', '1 час', '2 часа'], confirmAddress: 'Уточните адрес по телефону',
    notesSaveError: 'Не удалось сохранить. Скопируйте текст',
    releaseTitleFor: version => `Вышла версия приложения АА Казахстана ${version}`,
    releaseFeatures: 'Добавлены ближайшее собрание, календарь, отправка, умный поиск, QR-код и быстрые действия.',
    auditRelease: 'Исправлены языки уведомлений, даты, расписание, подписи и сохранение заметок.',
    auditChanges: ['Уведомления меняют язык вместе с приложением', 'Исправлены даты и подписи на трёх языках', 'Размышление открывается из уведомления', 'Заметки сохраняются сразу при вводе'],
    release30Summary: "АА Казахстана 3.0: три языка, размышления на весь год, поиск собраний, календарь и личные инструменты.",
    release30Changes: ["Интерфейс на русском, казахском и английском языках", "Ежедневные размышления на трёх языках на весь год", "50 групп: поиск, фильтры и расписание по времени Казахстана", "Ближайшее избранное собрание, напоминания и календарь", "27 книг с описаниями на трёх языках", "Счётчик трезвости, личные заметки и резервная копия"]
});
Object.assign(window.AA_I18N.kz, {
    closeAction: 'Жабу', closeTip: 'Кеңесті жабу', clearSearch: 'Іздеуді тазалау', mainNavigation: 'Негізгі навигация', logoAlt: 'Қазақстан АА логотипі', qrAlt: 'Қазақстан АА қолданбасының QR-коды', literatureCall: 'Вячеславқа қоңырау шалу',
    minuteOptions: ['15 мин', '30 мин', '1 сағат', '2 сағат'], confirmAddress: 'Мекенжайды телефон арқылы нақтылаңыз',
    notesSaveError: 'Сақтау мүмкін болмады. Мәтінді көшіріңіз',
    releaseTitleFor: version => `Қазақстан АА қолданбасының ${version} нұсқасы шықты`,
    releaseFeatures: 'Ең жақын жиналыс, күнтізбе, бөлісу, ақылды іздеу, QR-код және жылдам әрекеттер қосылды.',
    auditRelease: 'Хабарламалар тілі, күндер, кесте, жазулар және жазбаларды сақтау түзетілді.',
    auditChanges: ['Хабарламалар тілі қолданба тілімен бірге өзгереді', 'Үш тілдегі күндер мен жазулар түзетілді', 'Күнделікті ой хабарламадан ашылады', 'Жазбалар енгізілген сәтте сақталады'],
    release30Summary: "Қазақстан АА 3.0: үш тіл, жыл бойына арналған күнделікті ойлар, жиналыстарды іздеу, күнтізбе және жеке құралдар.",
    release30Changes: ["Қазақ, орыс және ағылшын тілдеріндегі интерфейс", "Жыл бойына арналған күнделікті ойлар үш тілде", "50 топ: іздеу, сүзгілер және Қазақстан уақыты бойынша кесте", "Ең жақын таңдаулы жиналыс, еске салғыштар және күнтізбе", "Үш тілдегі сипаттамалары бар 27 кітап", "Ішімдіксіз күндер есептегіші, жеке жазбалар және сақтық көшірме"]
});
Object.assign(window.AA_I18N.en, {
    closeTip: 'Close tip', clearSearch: 'Clear search', mainNavigation: 'Main navigation', logoAlt: 'AA Kazakhstan logo', qrAlt: 'AA Kazakhstan app QR code', literatureCall: 'Call Vyacheslav', confirmAddress: 'Confirm the address by phone',
    notesSaveError: 'Could not save. Copy your text',
    releaseTitleFor: version => `AA Kazakhstan app version ${version} is available`,
    releaseFeatures: 'Added next meeting, calendar, sharing, smart search, QR code, and quick actions.',
    auditRelease: 'Fixed notification languages, dates, schedules, labels, and note saving.',
    auditChanges: ['Notifications follow the selected language', 'Fixed dates and labels in all three languages', 'Reflections open directly from notifications', 'Notes are saved immediately as you type'],
    release30Summary: "AA Kazakhstan 3.0: three languages, a full year of Daily Reflections, meeting search, calendar, and personal tools.",
    release30Changes: ["Interface in Russian, Kazakh, and English", "A full year of Daily Reflections in all three languages", "50 groups: search, filters, and schedules in Kazakhstan time", "Next favorite meeting, reminders, and calendar export", "27 books with descriptions in all three languages", "Sobriety counter, personal notes, and backup"]
});

window.AA_PROFILE_EN = {
    committees: [
        { title: 'Committee on Cooperation with Government Agencies', description: 'The committee establishes and maintains contacts with government institutions, including akimats, the Ministry of Healthcare, the Ministry of Internal Affairs, health departments, clinics, local police offices, and other organizations. Committee members explain the work of Alcoholics Anonymous, provide information about groups and ways to receive help, and hold working meetings and presentations. The committee also helps prepare cooperation memoranda so public institutions can direct people affected by alcoholism to AA groups. This cooperation does not make AA part of a government institution, provide government funding to AA, or imply AA endorsement of government decisions. Alcoholics Anonymous remains independent; the committee creates practical working relationships and a clear way to cooperate.', contact: 'Chair: vacant' },
        { title: 'Finance Committee', description: 'The Finance Committee helps ensure transparent and responsible use of funds received for AA Kazakhstan services. It assists with budgets, income and expense records, financial reporting, and planning costs for literature, events, public information, and other service activities. The committee also supports AA’s principle of self-support through voluntary contributions from members and groups.', contact: 'Chair: Rizabek' },
        { title: 'Committee on Cooperation with Spiritual Institutions', description: 'The committee introduces representatives of mosques, churches, and other spiritual institutions to AA so they can tell a person seeking help for alcoholism about the Fellowship. It may hold information meetings, provide group contacts, and distribute approved AA information materials. AA is not a religious organization, is not affiliated with any denomination, and does not take part in religious disputes. The committee cooperates with spiritual institutions without joining AA to them or representing their views on behalf of the Fellowship.', contact: 'Chair: Bauyrzhan' },
        { title: 'International Committee', description: 'The International Committee maintains connections between AA Kazakhstan, national AA service structures in other countries, and the international Fellowship of Alcoholics Anonymous. It supports the exchange of experience, information, and materials, shares information about international forums and meetings, and helps present AA Kazakhstan’s experience internationally. The committee also develops contacts with neighboring countries. Its main purpose is to help carry the AA message and strengthen Fellowship unity in keeping with the purpose of the AA World Service Meeting.', contact: 'Chair: vacant' },
        { title: 'PIC — Public Information Committee', description: 'The Public Information Committee provides clear and accurate information about Alcoholics Anonymous, who AA helps, and how to find a meeting. It works with media outlets, online platforms, journalists, and community organizations; prepares publications, information materials, and public service messages; and supports AA Kazakhstan’s official channels. Its work is not personal promotion or advertising. Its purpose is to help people who need support learn that AA exists. While keeping information open and accessible, the committee protects members’ personal anonymity in press, radio, television, film, and online media.', contact: 'Chair: Sergey' },
        { title: 'Events Committee', description: 'The Events Committee organizes AA Kazakhstan forums, conferences, anniversaries, workshops, round tables, and other events. It develops programs, selects venues, and coordinates volunteers, registration, accommodation, technical support, and other practical arrangements. These events strengthen AA unity, encourage the exchange of recovery and service experience, and help carry the Fellowship’s primary message.', contact: 'Chair: Indira' },
        { title: 'Group Organization and Development Committee', description: 'The committee helps start new AA groups and supports existing groups with organizational matters. It can share experience, guidance, sample meeting formats, information about service positions and Traditions, group registration, and inclusion in the general schedule. It also strengthens the connection between groups and AA Kazakhstan’s service structure. The committee does not manage groups or interfere in their internal decisions: every group remains autonomous except in matters affecting other groups or AA as a whole.', contact: 'Chair: Arman' },
        { title: 'KZ Group Organization and Development Committee', description: 'This committee helps establish and develop groups that hold meetings in Kazakh. It supports group chairs and trusted servants, assists with meeting formats and information materials, and encourages exchange of experience among Kazakh-speaking AA members. Special attention is given to regions where language, cultural, or geographic conditions limit access to AA. This follows the international experience of committees serving remote communities by overcoming barriers to AA access.', contact: 'Chair: Yernar' },
        { title: 'Literature Committee', description: 'The Literature Committee is responsible for access to official AA literature, including books, pamphlets, leaflets, and recovery and service materials. It organizes ordering, accounting, storage, printing, and distribution. The committee may also assist with translations and the preparation of materials in Russian and Kazakh while respecting copyright and AA approval procedures.', contact: 'Chair: Vyacheslav' },
        { title: 'Treatment Facilities Committee', description: 'The Treatment Facilities Committee helps carry the AA message to people in addiction treatment centers, hospitals, rehabilitation programs, and other healthcare facilities. It arranges information sessions and outside AA meetings, provides literature, and helps people find a regular AA group after discharge. Committee members share their personal recovery experience but do not diagnose, prescribe treatment, or replace physicians, psychologists, or rehabilitation professionals.', contact: 'Chair: Yermek' },
        { title: 'Director of the AA Kazakhstan Service Foundation', description: 'The Director manages the day-to-day administrative and organizational work of the AA Kazakhstan Service Foundation. Within the Foundation’s charter and service decisions, the Director coordinates documentation, legal and operational matters, execution of the approved budget, contractor relations, and practical implementation of service structure decisions. The Director does not lead AA’s spiritual life or manage groups. AA groups remain autonomous, and the ultimate authority in the Fellowship is a loving God as expressed through the group conscience. The Foundation is a legal and operational service instrument, not a governing body of the Fellowship.', contact: 'Director: Elena' }
    ]
};

window.AA_PROFILE_KZ = {
  "committees": [
    {
      "title": "Мемлекеттік органдармен өзара іс-қимыл комитеті",
      "description": "Комитет әкімдіктермен, Денсаулық сақтау министрлігімен, Ішкі істер министрлігімен, денсаулық сақтау басқармаларымен, емханалармен, учаскелік полиция пункттерімен және басқа мемлекеттік мекемелермен байланыс орнатып, оны қолдайды. Комитет өкілдері мамандарға Анонимді Алкоголиктердің қызметі туралы айтып, топтар мен көмек алу мүмкіндіктері жөнінде ақпарат береді, жұмыс кездесулері мен таныстырылымдар өткізеді. Мемлекеттік мекемелер алкоголизм мәселесіне тап болған адамдарды АА топтарына бағыттай алуы үшін комитет ынтымақтастық меморандумдарын дайындауға және жасасуға қатысады. Бұл ынтымақтастық АА-ның мемлекеттік мекеме құрамына кіруін, одан қаржы алуын немесе оның шешімдерін қолдауын білдірмейді. АА тәуелсіздігін сақтайды; комитет жұмыс байланыстарын және өзара іс-қимылдың түсінікті тәртібін қалыптастырады.",
      "contact": "Төраға: орын бос"
    },
    {
      "title": "Қаржы комитеті",
      "description": "Қаржы комитеті Қазақстан АА қызметіне түсетін қаражаттың ашық әрі жауапты пайдаланылуына көмектеседі. Ол бюджетті дайындауға, кірістер мен шығыстарды есепке алуға, қаржылық есептілікке, әдебиетке, іс-шараларға, ақпараттық жұмысқа және басқа қызмет бағыттарына жұмсалатын шығындарды жоспарлауға қатысады. Комитет АА мүшелері мен топтарының ерікті жарналары арқылы өзін-өзі қамтамасыз ету қағидасын қолдайды.",
      "contact": "Төраға: Ризабек"
    },
    {
      "title": "Рухани мекемелермен өзара іс-қимыл комитеті",
      "description": "Комитет мешіттер, шіркеулер және басқа рухани мекемелер өкілдерін АА қызметімен таныстырады. Осылайша олар алкоголизмнен көмек іздеген адамға Қауымдастық туралы айта алады. Комитет ақпараттық кездесулер өткізіп, топтардың байланыстарын және мақұлданған АА материалдарын ұсынады. АА діни ұйым емес, ешбір конфессияға жатпайды және діни дауларға қатыспайды. Комитет рухани мекемелермен ынтымақтасады, бірақ АА-ны оларға қоспайды және олардың көзқарастарын Қауымдастық атынан білдірмейді.",
      "contact": "Төраға: Бауыржан"
    },
    {
      "title": "Халықаралық комитет",
      "description": "Халықаралық комитет Қазақстан АА-сының басқа елдердің ұлттық қызмет құрылымдарымен және Анонимді Алкоголиктердің халықаралық Қауымдастығымен байланысын қолдайды. Ол тәжірибе, ақпарат және материалдар алмасуға, халықаралық форумдар мен кездесулер туралы хабарлауға, Қазақстан АА тәжірибесін халықаралық деңгейде таныстыруға көмектеседі. Комитет көрші елдермен де байланыс дамытады. Негізгі мақсаты — АА Дүниежүзілік қызмет кездесуінің мақсатына сәйкес АА хабарын жеткізуге және Қауымдастық бірлігін нығайтуға көмектесу.",
      "contact": "Төраға: орын бос"
    },
    {
      "title": "Қоғамды ақпараттандыру комитеті",
      "description": "Комитет Анонимді Алкоголиктер туралы, АА кімге көмектесетіні және жиналысты қалай табуға болатыны жөнінде түсінікті, дәл ақпарат береді. Ол бұқаралық ақпарат құралдарымен, интернет алаңдарымен, журналистермен және қоғамдық ұйымдармен жұмыс істейді, жарияланымдар мен ақпараттық материалдар дайындайды, Қазақстан АА-сының ресми арналарын қолдайды. Бұл жеке адамдарды танымал ету немесе жарнама жасау емес. Мақсаты — көмекке мұқтаж адамдарға АА бар екенін жеткізу. Комитет баспасөзде, радиода, теледидарда, кинода және интернетте мүшелердің жеке анонимділігін сақтайды.",
      "contact": "Төраға: Сергей"
    },
    {
      "title": "Іс-шаралар комитеті",
      "description": "Комитет Қазақстан АА форумдарын, конференцияларын, мерейтойларын, семинарларын, дөңгелек үстелдерін және басқа іс-шараларын ұйымдастырады. Ол бағдарламалар дайындайды, орын таңдайды, еріктілердің жұмысын, тіркеуді, орналасуды, техникалық қолдауды және басқа ұйымдастыру мәселелерін үйлестіреді. Іс-шаралар АА бірлігін нығайтады, сауығу мен қызмет тәжірибесін бөлісуге және Қауымдастықтың негізгі хабарын жеткізуге көмектеседі.",
      "contact": "Төрайым: Индира"
    },
    {
      "title": "Топтарды ұйымдастыру және дамыту комитеті",
      "description": "Комитет жаңа АА топтарын ашуға және жұмыс істеп тұрған топтардың ұйымдастыру мәселелерін шешуге көмектеседі. Ол тәжірибемен, ұсынымдармен, жиналыс үлгілерімен, қызмет пен Дәстүрлер туралы ақпаратпен бөліседі, топтарды тіркеуге және жалпы кестеге енгізуге жәрдемдеседі. Комитет топтар мен Қазақстан АА қызмет құрылымының байланысын нығайтады. Ол топтарды басқармайды және олардың ішкі шешімдеріне араласпайды: басқа топтарға немесе тұтас АА-ға қатысты мәселелерден басқа жағдайда әр топ дербес.",
      "contact": "Төраға: Арман"
    },
    {
      "title": "Қазақ тіліндегі топтарды ұйымдастыру және дамыту комитеті",
      "description": "Комитет қазақ тілінде жиналыс өткізетін топтарды құруға және дамытуға көмектеседі. Ол топ төрағалары мен сенімді қызметшілерді қолдайды, жиналыс үлгілері мен ақпараттық материалдарды дайындауға жәрдемдеседі, қазақтілді АА мүшелерінің тәжірибе алмасуын қолдайды. Тілдік, мәдени немесе географиялық жағдайлар АА-ға қолжетімділікті шектейтін өңірлерге ерекше көңіл бөлінеді. Бұл АА-ға қолжетімділік кедергілерін жоюға бағытталған шалғай қауымдастықтарға қызмет көрсету комитеттерінің халықаралық тәжірибесіне сәйкес келеді.",
      "contact": "Төраға: Ернар"
    },
    {
      "title": "Әдебиет комитеті",
      "description": "Комитет ресми АА әдебиетінің — кітаптардың, брошюралардың, буклеттердің, сауығу және қызмет материалдарының — қолжетімділігіне жауап береді. Ол әдебиетке тапсырыс беруді, есепке алуды, сақтауды, басып шығаруды және таратуды ұйымдастырады. Авторлық құқықтар мен АА-дағы келісу тәртібін сақтай отырып, орыс және қазақ тілдеріндегі аудармалар мен материалдарды дайындауға қатыса алады.",
      "contact": "Төраға: Вячеслав"
    },
    {
      "title": "Емдеу мекемелерімен жұмыс комитеті",
      "description": "Комитет АА хабарын наркологиялық орталықтардағы, ауруханалардағы, оңалту бағдарламаларындағы және басқа емдеу мекемелеріндегі адамдарға жеткізуге көмектеседі. Ол ақпараттық кездесулер мен көшпелі жиналыстарды келіседі, әдебиет береді және адамға емдеу мекемесінен шыққаннан кейін тұрақты АА тобын табуға көмектеседі. Комитет мүшелері жеке сауығу тәжірибесімен бөліседі, бірақ диагноз қоймайды, ем тағайындамайды және дәрігерлерді, психологтарды немесе оңалту мамандарын алмастырмайды.",
      "contact": "Төраға: Ермек"
    },
    {
      "title": "Қазақстан АА қызмет көрсету қорының директоры",
      "description": "Директор Қазақстан АА қызмет көрсету қорының күнделікті әкімшілік және ұйымдастыру жұмысын қамтамасыз етеді. Қор жарғысы мен қызмет органдарының шешімдері шегінде құжат айналымын, құқықтық және шаруашылық мәселелерді, бекітілген бюджеттің орындалуын, мердігерлермен жұмысты және қызмет құрылымы шешімдерінің іске асырылуын үйлестіреді. Директор АА-ның рухани өміріне басшылық жасамайды және топтарды басқармайды. АА топтары дербестігін сақтайды, ал Қауымдастықтағы ең жоғары билік — топтық сана арқылы Өзін білдіретін сүюші Құдай. Қор — Қауымдастықты басқару органы емес, қызмет көрсетудің заңды және жұмыс құралы.",
      "contact": "Директор: Елена"
    }
  ]
};
