window.AA_I18N = {
        ru: {
            head: 'АА КАЗАХСТАНА', total: 'Всего:', units: [['год','года','лет'],['мес.','мес.','мес.'],['день','дня','дней']],
            motLab: 'Ежедневные размышления', kaspi: 'Седьмая Традиция', kaspiNote: 'Добровольное пожертвование в фонд АА Казахстана', nav: ['Сегодня','Новости','Книги','Группы'], allCities: 'Все города', favorites: '★ Избранное', noFavorites: 'Добавьте нужные группы в избранное, нажав на звезду в карточке.', addFavorite: 'Добавить в избранное', removeFavorite: 'Убрать из избранного',
            sOpen: 'ОТКРЫТО. ЕЩЕ', sSoon: 'ЧЕРЕЗ', sClosed: 'ЗАКРЫТО', todayBtn: '📅 Сегодня', sosMain: '🚨 НУЖНА ПОМОЩЬ?',
            sosRu: 'РУССКИЙ ЯЗЫК', sosKz: 'ҚАЗАҚ ТІЛІ', nProf: 'Мой путь', trustHead: 'ДОВЕРЕННЫЕ ЛИЦА', prayerHead: 'МОЛИТВА', notesHead: 'ЗАМЕТКИ ПО ДНЮ',
            nextMedal: 'До медали', left: 'Осталось', prayer: 'Боже, дай мне разум и душевный покой принять то, что я не в силах изменить,\nмужество изменить то, что могу,\nи мудрость отличить одно от другого.',
            placeholder: 'Ваши мысли, благодарности или инсайты...', litCom: 'Литературный комитет', litPrice: 'Наличие, цены и заказ литературы', bookAll: 'Все', bookRu: 'Рус', bookKz: 'Қаз', bookBuy: 'Купить', bookCall: 'Позвонить', bookShare: 'Поделиться',
            trustName: 'Имя', trustPhone: 'Номер', openMap: 'Открыть в 2ГИС', addressLabel: 'Адрес', scheduleLabel: 'Расписание', phoneLabel: 'Телефон', phonesLabel: 'Телефоны',
            openZoom: 'Открыть Zoom', openChat: 'Открыть чат', zoomLabel: 'Zoom', chatLabel: 'Чат', savePending: '...', saveDone: '✓ Сохранено',
            minutesShort: 'МИН', hoursShort: 'Ч', noSchedule: 'По запросу',
            notificationsHead: 'УВЕДОМЛЕНИЯ', notificationCenter: 'Уведомления', notificationReadAll: 'Прочитать все', notificationEmpty: 'Здесь появятся новые размышления, новости и напоминания о собраниях.',
            notifMasterTitle: 'Внутренние уведомления', notifMasterNote: 'Показывать новые события в центре уведомлений', notifReflectionTitle: 'Ежедневные размышления', notifReflectionNote: 'Сообщать о новом размышлении при открытии приложения', notifNewsTitle: 'Новости', notifNewsNote: 'Сообщать о новых публикациях', notifTodayTitle: 'Группы сегодня', notifTodayNote: 'Показывать сводку собраний на текущий день', notifFavoritesTitle: 'Избранные группы', notifFavoritesNote: 'Напоминать перед началом собрания, пока приложение открыто', notifBrowserTitle: 'Системное окно при открытом приложении', notifBrowserNote: 'Не работает после полного закрытия приложения', notifBeforeTitle: 'Напоминать заранее',
            notifReflectionNew: 'Новое ежедневное размышление', notifNewsNew: 'Новая публикация', notifTodayNew: 'Собрания сегодня', notifFavoriteNew: 'Скоро начнётся собрание',
            soberUnitsShort: ['лет', 'мес.', 'дней'], quickToday: 'Найти собрание сегодня', quickCall: 'Позвонить в АА', quickFavorites: 'Мои группы', quickFirst: 'Я впервые в АА', nearestMeeting: 'Ближайшее собрание', nearestEmpty: 'Сегодня подходящих предстоящих собраний не найдено.', todayAt: 'Сегодня в', tomorrowAt: 'Завтра в', route: 'Маршрут', callAction: 'Позвонить', details: 'Подробнее', myCity: 'Мой город', onlineFilter: 'Онлайн', chooseCityTitle: 'В каком городе вы находитесь?', chooseCityNote: 'Мы покажем ваши группы и ближайшее собрание.', saveCity: 'Сохранить город', showAllCities: 'Показать все города', firstTitle: 'Первый раз в АА', firstText: 'Собрания бесплатные. Записываться не нужно. Можно ничего не говорить и просто слушать. Фамилию называть необязательно.', cityHead: 'МОЙ ГОРОД', citySettingTitle: 'Выберите свой город', citySettingNote: 'Он используется для ближайших собраний и уведомлений', cityChange: 'Изменить', cityNotSelected: 'Город не выбран', settingsHead: 'НАСТРОЙКИ', versionLabel: 'Версия приложения', updateLabel: 'Обновление применяется автоматически при запуске', textSizeTitle: 'Размер текста', textSizeNormal: 'Обычный', textSizeLarge: 'Крупный', statusUpdating: 'Обновляем данные…', statusUpdated: 'Данные обновлены', statusOffline: 'Нет интернета. Показана сохранённая версия', statusZoomFailed: 'Не удалось открыть Zoom', statusNoPhone: 'Номер телефона не указан', understood: 'Понятно', reportError: 'Сообщить об ошибке', scheduleUpdated: 'Расписание обновлено', newsChecked: 'Новости проверены'
        },
        kz: {
            head: 'ҚАЗАҚСТАН АА', total: 'Барлығы:', units: [['жыл','жыл','жыл'],['ай','ай','ай'],['күн','күн','күн']],
            motLab: 'Күнделікті ойлар', kaspi: 'Жетінші Дәстүр', kaspiNote: 'Қазақстан АА қорына ерікті қайырымдылық', nav: ['Бүгін','Жаңалықтар','Кітаптар','Топтар'], allCities: 'Барлық қалалар', favorites: '★ Таңдаулылар', noFavorites: 'Қажетті топтарды карточкадағы жұлдызшаны басып таңдаулыларға қосыңыз.', addFavorite: 'Таңдаулыларға қосу', removeFavorite: 'Таңдаулылардан алып тастау',
            sOpen: 'АШЫҚ. ТАҒЫ', sSoon: 'БАСТАЛАДЫ', sClosed: 'ЖАБЫҚ', todayBtn: '📅 Бүгін', sosMain: '🚨 КӨМЕК КЕРЕК ПЕ?',
            sosRu: 'ОРЫС ТІЛІ', sosKz: 'ҚАЗАҚ ТІЛІ', nProf: 'Менің жолым', trustHead: 'СЕНІМДІ ТҰЛҒАЛАР', prayerHead: 'ДҰҒА', notesHead: 'КҮНДЕЛІКТІ ЖАЗБАЛАР',
            nextMedal: 'Медальға дейін', left: 'Қалды', prayer: 'Уа, Тәңірім, мен өзгерте алмайтын нәрселерді қабылдауға жан тыныштығын,\nөзгерте алатын нәрселерді өзгертуге батылдық,\nжәне олардың айырмашылығын білетін даналық бере гөр.',
            placeholder: 'Ойларыңыз, ризашылықтарыңыз немесе инсайттарыңыз...', litCom: 'Әдебиет комитеті', litPrice: 'Әдебиеттің бар-жоғы, бағасы және тапсырыс', bookAll: 'Барлығы', bookRu: 'Рус', bookKz: 'Қаз', bookBuy: 'Сатып алу', bookCall: 'Қоңырау шалу', bookShare: 'Бөлісу',
            trustName: 'Аты', trustPhone: 'Нөмірі', openMap: '2ГИС ашу', addressLabel: 'Мекенжай', scheduleLabel: 'Кесте', phoneLabel: 'Телефон', phonesLabel: 'Телефондар',
            openZoom: 'Zoom ашу', openChat: 'Чатты ашу', zoomLabel: 'Zoom', chatLabel: 'Чат', savePending: '...', saveDone: '✓ Сақталды',
            minutesShort: 'МИН', hoursShort: 'САҒ', noSchedule: 'Сұраныс бойынша',
            notificationsHead: 'ХАБАРЛАМАЛАР', notificationCenter: 'Хабарламалар', notificationReadAll: 'Барлығын оқу', notificationEmpty: 'Мұнда жаңа ойлар, жаңалықтар және жиналыстар туралы еске салулар пайда болады.',
            notifMasterTitle: 'Ішкі хабарламалар', notifMasterNote: 'Жаңа оқиғаларды хабарламалар орталығында көрсету', notifReflectionTitle: 'Күнделікті ойлар', notifReflectionNote: 'Қосымша ашылғанда жаңа ой туралы хабарлау', notifNewsTitle: 'Жаңалықтар', notifNewsNote: 'Жаңа жарияланымдар туралы хабарлау', notifTodayTitle: 'Бүгінгі топтар', notifTodayNote: 'Бүгінгі жиналыстардың қорытындысын көрсету', notifFavoritesTitle: 'Таңдаулы топтар', notifFavoritesNote: 'Қосымша ашық кезде жиналыс алдында еске салу', notifBrowserTitle: 'Қосымша ашық кездегі жүйелік терезе', notifBrowserNote: 'Қосымша толық жабылғаннан кейін жұмыс істемейді', notifBeforeTitle: 'Алдын ала еске салу',
            notifReflectionNew: 'Жаңа күнделікті ой', notifNewsNew: 'Жаңа жарияланым', notifTodayNew: 'Бүгінгі жиналыстар', notifFavoriteNew: 'Жиналыс жақында басталады',
            soberUnitsShort: ['жыл', 'ай', 'күн'], quickToday: 'Бүгінгі жиналысты табу', quickCall: 'АА-ға қоңырау шалу', quickFavorites: 'Менің топтарым', quickFirst: 'Мен АА-ға алғаш рет келдім', nearestMeeting: 'Ең жақын жиналыс', nearestEmpty: 'Жақын уақытта қолайлы жиналыс табылмады.', todayAt: 'Бүгін', tomorrowAt: 'Ертең', route: 'Бағыт', callAction: 'Қоңырау шалу', details: 'Толығырақ', myCity: 'Менің қалам', onlineFilter: 'Онлайн', chooseCityTitle: 'Сіз қай қаладасыз?', chooseCityNote: 'Сіздің топтарыңыз бен ең жақын жиналысты көрсетеміз.', saveCity: 'Қаланы сақтау', showAllCities: 'Барлық қалаларды көрсету', firstTitle: 'АА-ға алғаш рет', firstText: 'Жиналыстар тегін. Алдын ала жазылудың қажеті жоқ. Ештеңе айтпай, жай ғана тыңдауға болады. Тегіңізді айту міндетті емес.', cityHead: 'МЕНІҢ ҚАЛАМ', citySettingTitle: 'Қалаңызды таңдаңыз', citySettingNote: 'Ол ең жақын жиналыстар мен хабарламалар үшін қолданылады', cityChange: 'Өзгерту', cityNotSelected: 'Қала таңдалмаған', settingsHead: 'БАПТАУЛАР', versionLabel: 'Қосымша нұсқасы', updateLabel: 'Жаңарту қосымша іске қосылғанда автоматты түрде қолданылады', textSizeTitle: 'Мәтін өлшемі', textSizeNormal: 'Қалыпты', textSizeLarge: 'Үлкен', statusUpdating: 'Деректер жаңартылуда…', statusUpdated: 'Деректер жаңартылды', statusOffline: 'Интернет жоқ. Сақталған нұсқа көрсетілді', statusZoomFailed: 'Zoom ашылмады', statusNoPhone: 'Телефон нөмірі көрсетілмеген', understood: 'Түсінікті', reportError: 'Қате туралы хабарлау', scheduleUpdated: 'Кесте жаңартылды', newsChecked: 'Жаңалықтар тексерілді'
        }
    };
