const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
let page;
try {
const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:process.env.TEST_TZ||'America/New_York',acceptDownloads:true});
page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>localStorage.setItem('aa_coachmarks_v2',JSON.stringify({swipe:true,favorite:true})));
await page.clock.setFixedTime(new Date('2026-09-30T13:00:00Z'));
await page.goto(process.env.APP_URL||'http://127.0.0.1:8080');
await page.locator('#app-splash').waitFor({state:'hidden'});
if(await page.locator('#whats-new-close').isVisible())await page.locator('#whats-new-close').click();
if(await page.locator('#coachmark-close').isVisible())await page.locator('#coachmark-close').click();
if(await page.locator('#install-close').isVisible())await page.locator('#install-close').click();
// First-run city onboarding is modal and blocks the group quick filters. Dismiss it
// for the general smoke flow; the onboarding itself is exercised later via Settings.
if(await page.locator('#city-onboarding').isVisible())await page.locator('#city-onboarding-all').click();
await page.locator('#btn-g').click();
assert.equal(await page.locator('.group-card').count(),50);
await page.locator('#group-filter-online').click();
const onlineNames=await page.locator('.group-name').allTextContents();
assert.equal(await page.locator('.group-card').count(),5);
await page.locator('#todayFilter').click();
assert.equal(await page.locator('.group-card').count(),0); // Birlik is Thursday
await page.locator('#todayFilter').click();
await page.locator('#citySelect').selectOption('all');
await page.locator('#citySelect').selectOption('Онлайн');
assert.equal(await page.locator('.group-card').count(),5);
assert.deepEqual(await page.locator('.group-name').allTextContents(),onlineNames);
await page.locator('#group-filter-remote').click();
assert.equal(await page.locator('.group-card').count(),5);
await page.locator('#todayFilter').click();
assert.equal(await page.locator('.group-card').count(),1);
assert((await page.locator('.group-card').innerText()).includes('Пана'));
await page.locator('#todayFilter').click();
await page.locator('#group-filter-remote').click();
await page.locator('#group-search').fill('среда');
assert((await page.locator('#list-container').innerText()).includes('8 Марта'));
await page.locator('#group-search').fill('суббота');
assert((await page.locator('#list-container').innerText()).includes('Решение есть'));
await page.locator('#group-search').fill('Бірлік');
assert((await page.locator('.group-card').textContent()).includes('Завтра, 21:00'));
await page.locator('[data-group-action="calendar"]').click();
assert((await page.locator('#calendar-note').innerText()).includes('Завтра, 21:00'));
await page.locator('#calendar-close').click();
assert.equal(await page.locator('#group-search').inputValue(),'Бірлік');
assert.equal(await page.locator('.group-card').count(),1);
await page.locator('[data-group-action="calendar"]').click();
await page.goBack();
assert(!await page.locator('#calendar-modal').isVisible());
assert.equal(await page.locator('#group-search').inputValue(),'Бірлік');
await page.locator('#group-search').fill('Виктория');
await page.locator('[data-group-action="calendar"]').click();
const downloadPromise=page.waitForEvent('download');
await page.locator('[data-calendar-mode="weekly"]').click();
const dl=await downloadPromise;const ics=await fs.readFile(await dl.path(),'utf8');
assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,3);
assert(ics.includes('DTSTART:20261001T143000Z'));
assert(ics.includes('DTSTART:20261003T140000Z'));
assert(ics.includes('DTSTART:20261006T143000Z'));
assert.equal(await page.locator('#group-search').inputValue(),'Виктория');
await page.locator('#btn-c').click();
await page.locator('#notification-button').click();
await page.locator('.notification-item').filter({hasText:'Собрания сегодня'}).click();
assert(await page.locator('#tab-groups').isVisible());
assert.equal(await page.locator('#todayFilter').getAttribute('aria-pressed'),'true');
assert.equal(await page.locator('.group-card').count(),15);
await page.locator('#btn-p').click();await page.locator('#btn-settings-head').click();
await page.locator('#city-setting-open').click();
assert(!await page.locator('#install-banner').isVisible());
assert(!await page.locator('#coachmark').isVisible());
await page.locator('#city-onboarding-select').selectOption('Алматы');
await page.locator('#city-onboarding-save').click();
assert(!await page.locator('#city-onboarding').isVisible());
assert((await page.locator('#city-setting-current').innerText()).includes('Алматы'));
await page.locator('#btn-l').click();assert.equal(await page.locator('#book-list button').count(),27);
for(let i=0;i<27;i++){await page.locator('#book-list button').nth(i).click();assert(await page.locator('#book-modal').isVisible());await page.locator('#book-modal-close').click();}
await page.locator('#btn-n').click();
assert.equal(await page.locator('.news-card').count(),7);
assert(await page.locator('.news-description a[href*="zoom.us"]').count()>0);
assert(await page.locator('.news-slide a').count()>0);
await page.locator('#l-kz').click();await page.locator('#btn-p').click();await page.locator('#btn-aa-structure').click();
assert((await page.locator('#acc-aa-structure').innerText()).includes('Қаржы комитеті'));
for(const button of await page.locator('#acc-aa-structure .committee-btn').all())await button.click();
assert.equal(await page.locator('#acc-aa-structure .committee-content:visible').count(),11);
await page.locator('#structure-image-trigger').click();
assert((await page.locator('#structure-image-modal img').getAttribute('src')).includes('-kz.svg'));
await page.locator('#structure-image-close').click();
await page.locator('#l-en').click();assert((await page.locator('#acc-aa-structure').innerText()).includes('Finance Committee'));
await page.locator('#l-ru').click();await page.locator('#btn-c').click();
await page.locator('#date-input').fill('2025-09-30');
assert((await page.locator('#complex-sober-display').innerText()).includes('ГОД') || (await page.locator('#complex-sober-display').innerText()).includes('год'));
await page.locator('#btn-g').click();await page.locator('#citySelect').selectOption('all');
if(await page.locator('#todayFilter').getAttribute('aria-pressed')==='true')await page.locator('#todayFilter').click();
await page.locator('#group-search').fill('Виктория');
await fs.mkdir('test-results',{recursive:true});
await page.screenshot({path:process.env.SCREENSHOT_PATH||'test-results/aa-fixed-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1000});
await page.screenshot({path:'test-results/aa-fixed-desktop.png',fullPage:true});
assert.equal(errors.length,0,errors.join('\n'));
console.log('OK: mobile browser, 5 tabs, 27 books, 11 committees, filters, search, notifications, history, calendar, city modal, languages. TZ='+process.env.TEST_TZ);
} finally {if(page){await fs.mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/last-state.png',fullPage:true}).catch(()=>{});await fs.writeFile('test-results/last-state.txt',await page.locator('body').innerText()).catch(()=>{});}await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
